[package]
name = "ircbot"
version = "0.6.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
irc = "0.13.6"
airkorea = "0.4.0"
regex = "1.1.5"
lazy_static = "1.3.0"
futures = "0.1.26"
failure = "0.1.5"
openssl-probe = "0.1.2"
backslash-z = "0.2.0"
