nickname = "bot"
alt_nics = ["bot_", "bot__"]
username = "bot"
realname = "IRC bot"
server = ""
port = 6697
use_ssl = true
channels = [""]
user_info = "IRC bot"

[options]
daummap_app_key = "APP_KEY"
